import ares
import sys,os
import freephil as phil
import ares.import_file

__all__ = []
__version__ = ares.__version__
prog_short_description = 'Integrates series of frames from SEC-SAXS'

phil_sec_str =  '''
sec {
    sort = True
    .help = Sort the input files by header time. If False, the order as in input list used.
    .type = bool
    
    output {
        prefix = frame
        .help = Prefix of output files
        .type = str
        directory = sec_by_frame
        .help = output directory
        .type = path
        start_frame = 1
        .help = Number of the first frame.
        .type = int
    }
}
    '''
phil_sec = phil.parse(phil_sec_str)

phil_core = phil.parse('''
import {
    include scope ares.import_file.phil_core
    }
    
input_files = None
.help = List of input files in the Ares PHIL format (usually generated by ares.import) If provided, the import is ignored
.type = path

''' + phil_sec_str + '''
integrate {
    include scope ares.integrate.phil_core
}

mask {
    include scope ares.mask.phil_core
}

q_transformation {
    include scope ares.q_transformation.phil_core
}
''',process_includes=True)

def run(params):
    """
    Running function for SEC
    """

    if params.input_files is not None:
        files = ares.import_file.ImportFiles(file_phil=params.input_files)
    else:
        files = ares.import_file.ImportFiles(run_phil=params.import)
        files.write_groups()





class JobSec(ares.Job):
    def __set_meta__(self):
        '''
        Sets various package metadata
        '''

        self._program_short_description = 'Another angular REduction for Saxs'

        self._program_name = os.path.basename(sys.argv[0])
        self._program_version = __version__

    def __worker__(self):
        '''
        The actual programme worker
        :return:
        '''
        pass

    def __set_system_phil__(self):
        '''
        Settings of CLI arguments. self._parser to be used as argparse.ArgumentParser()
        '''
        self._system_phil = phil_core

    def __argument_processing__(self):
        '''
        Adjustments of raw input arguments. Modifies self._args, if needed

        '''
        pass

    def __help_epilog__(self):
        '''
        Epilog for the help

        '''
        pass

    def __process_unhandled__(self):
        '''
        Process unhandled CLI arguments into self.params

        :return:
        '''
        self.params.paths=self.unhandled

def main(argv=None):
    job = JobSec()
    return job.job_exit


if __name__ == "__main__":
    sys.exit(main())